version: "3"

services:
  verneg:
    image: revezo/verneg:0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verneg
    ports:
      - "28970:28970/udp"
      - "55887:55887/udp"
      - 28975:28975
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verneg_db
      MYSQL_USER: verneg
      MYSQL_PASSWORD: verneg
    ports:
      - 3306:3306
  flyway:
    image: flyway/flyway:7.5
    container_name: flyway-verneg
    command: -url=jdbc:mysql://mysql -schemas=verneg_db -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./docker/flyway/sql:/flyway/sql
    depends_on:
      - mysql
